export enum ConversionTypes {
	bech32ToHex,
	hexToBech32,
	decimalToHexa,
	hexaToDecimal,
	decimalToBase64,
	base64ToDecimal,
	amountToDenominated,
	denominatedToAmount,
	stringToHexadecimal,
	hexadecimalToString,
	stringToBase64,
	base64ToString,
	hexadecimalToBase64,
	base64ToHexadecimal,
	base64ToHexDecimal,
}
